#!/bin/bash
# Задание 4
# Массовая обработка файлов
# Author: Bulat Giniyatullin

while getopts "d:e:c:n:" OPT; do
  case "$OPT" in
    d)
      declare -r dirpath="$OPTARG"
      ;;
    e)
      declare -r mask="$OPTARG"
      ;;
    c)
      declare -r command="$OPTARG"
      ;;
    n)
      declare -r number="$OPTARG"
      ;;
    *)
      exit 1
      ;;
  esac
done
for parname in dirpath mask command number; do
  declare -n par=$parname
  if [ -z "$par" ]; then
    echo "$parname is unset"
    exit 1
  fi
done

function print_processed_count() {
    echo "Already processed: $PROCESSED_COUNT"
}

function print_left_count() {
    echo "Files left: $LEFT_COUNT"
}

trap print_processed_count SIGUSR1
trap print_left_count SIGUSR2

function next_file() {
    declare -n arr="files"
    if [ ${#arr[@]} -gt 0 ]; then
      NEXT_FILE="${arr[${#arr[@]}-1]}"
      unset "arr[${#arr[@]}-1]"
      return 0
    fi
    return 1
}

declare -r path="$dirpath/$mask"
declare -a files=( $path )
file_count=${#files[@]}
declare -i LEFT_COUNT=$file_count
declare -i PROCESSED_COUNT=0
min=$((number < file_count ? number : file_count))
for _ in $(seq 1 $min); do
    next_file
    eval $command $NEXT_FILE &
done
while : ; do
  wait -n
  LEFT_COUNT=$((LEFT_COUNT-1))
  PROCESSED_COUNT=$((PROCESSED_COUNT+1))
  if [ ${#files[@]} -gt 0 ]; then
      next_file
      eval $command $NEXT_FILE &
  fi
  if [ $LEFT_COUNT -eq 0 ]; then
      break
  fi
done
wait
echo 'END'
